### PR TITLE
Formatted README

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｃｏｍｍｅｎｄａｔｉｏｎｓ-4b781e?style=for-the-badge&logoColor=white&logo=GitHub&labelColor=609926
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-9e122a?style=for-the-badge&logoColor=white&logo=GitLFS&labelColor=D81939
[Badge GitHub]: https://img.shields.io/badge/ＧｉｔＨｕｂ_Ｎｅｗｃｏｍｅｒｓ-be2e47?style=for-the-badge&logoColor=white&logo=BitWarden&labelColor=FD3A5C
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-8c3b63?style=for-the-badge&logoColor=white&logo=RuboCop&labelColor=c84f8c
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-4e2760?style=for-the-badge&logoColor=white&logo=AskUbuntu&labelColor=73398D
[Badge Info]: https://img.shields.io/badge/Ｉｎｆｏｒｍａｔｉｏｎ-01434e?style=for-the-badge&logoColor=white&logo=InternetArchive&labelColor=006272

[Button MarkedDown]: https://img.shields.io/badge/MarkedDown-00b2ff?style=for-the-badge&logoColor=white&logo=Markdown

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki
[MarkedDown]: https://github.com/MarkedDown 'How to better use Markdown'

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>

## Note

The matrix badge doesn't seem to show on forks, so heres a screeenshot for how it looks:

Screenshot_20220913_155239

  
<br>
<br>

## ![Badge Suggestions]

  <br>

- ***[Disable unused Widgets][Widgets]***:

  - `Packages`

  - `Releases`

  <br>

- ***[Disable unused Tabs][Tabs]***:

  - `Projects`

  - `Actions`
  
  <br>
  
- ***[Why not to use GitHub Wiki][Wiki]***

  <br>

- Move the `Components` & `How it works?` section 
  to the documentation and instead add a quicklink.

<br>
<br>

## ![Badge Changes]

- General formatting / spacing

- Formatted / added badges

- Added quicklinks for general & news

- Linked acknowledged party

- Sectioned text content

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***,
  *please first let me know about them, before disregarding it entirely so*
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

## ![Badge Info]

If you want to know more about **Markdown** check out:

<br>

                           [![Button MarkedDown]][MarkedDown]

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/locutus

### CODE REVIEW

**Comment by ElectronicsArchiver** [comment]
Closed without any comment, lovely communication.

**Comment by iduartgomez** [comment]
I though this was a bot! @ElectronicsArchiver 

Seems the readme is cluttered like this, but I will let @sanity decide.

**Comment by ElectronicsArchiver** [comment]
@iduartgomez I didn't inlcude my `I'm not a bot` paragraph in my PR since my previous PR had been accepted..

Guess I should always include it from now on..

**Comment by iduartgomez** [comment]
> @iduartgomez I didn't inlcude my `I'm not a bot` paragraph in my PR since my previous PR had been accepted..
> 
> Guess I should always include it from now on..

My sincere apologies, did miss/forgot that.

**Comment by ElectronicsArchiver** [comment]
No problem, it was just a mistake after all~

**Comment by sanity** [comment]
@electronicsarchiver in @iduartgomez's defense - your username does look a little bot-like :) Really appreciate your contribution.

I like some of these changes but some of them are a bit too dramatic - eg. at least previewing the README.md it now seems to require a lot more scrolling to get to the substance. Is there another project you were modeling this on?

**Comment by ElectronicsArchiver** [comment]
> @ElectronicsArchiver in @iduartgomez's defense - your username does look a little bot-like :) Really appreciate your contribution.

♥

<br>

> I like some of these changes but some of them are a bit too dramatic - eg. at least previewing the README.md it now seems to require a lot more scrolling to get to the substance.

Well as I mentioned in the recommendations, I wouldn't keep the design explanation in the README, that seems too in-depth for an overview.

<br>

> Is there another project you were modeling this on?

Not really? I mostly do README / documentation formatting, so that's just how I do things, I can add some links to previous work:

( For some I sent links to my forks since the parent projects have changed )

https://github.com/Ultimaker/Cura

https://github.com/Rnen/AdminToolbox

https://github.com/Seniorendi/AdvancedPeripherals

https://github.com/ElectronicsArchiver/Fading-Revelations

https://github.com/PlumyGame/mgpp

https://github.com/jascoproducts/firmware

https://github.com/savetz/RAMbrandt

<br>

Also you could say it's 'based on' things found in my MarkedDown org:

https://github.com/MarkedDown

**Comment by sanity** [comment]
@ElectronicsArchiver Hey, wanted to get back to you, thank you again for your contribution.

After discussion with the team, we've decided to stick with the current more information-dense README. 

Inspired by your work we've reorganized the current README.md, and we would appreciate any feedback you might have, but we're probably not going to make significant structural changes.

We're modeling our README off [Cargo](https://github.com/rust-lang/cargo), sticking fairly close to the default Github style for familiarity.

**Pull request closed without merging**
