### PR TITLE
Intelligent routing

### PR DESCRIPTION
**Pull request by sanity**

### CODE REVIEW

**Comment by iduartgomez** [comment]
There are several regressions here on the dependencies used. Can we remove all changes to ` Cargo.toml` and `Cargo.lock` files from this PR (except adding any new dependencies specifically needed for this PR)? 

`main` is up to date for the most part.

**Comment by iduartgomez** [comment]
Also to `package.json`,  `.lock+  files etc. There is actually some wrong merge/rebase handling here since there are unrelated code changes to the PR

**Comment by iduartgomez** [comment]
probably easier to just create a new branch from the current `main` branch and copy the `locutus-router` code in a new commit

**Comment by sanity** [comment]
Per @iduartgomez's suggestion I have copied the relevant code over a branch freshly created from `main` - see [new PR](https://github.com/freenet/locutus/pull/590).

**Pull request closed without merging**
