### PR TITLE
feat(contractStorage): introduce rocksdb additionally to sqlite

### LINKED ISSUE #17: Switch to RocksDB store back end as default storage
In the future build with both Sqlite and RocksDB as possible backends (via feature) in order to compare behavior and performance characteristics. Probably we will want to stick with one, eventually, but otherwise, RocksDB can be used as a building block  KV for more complex databases (is already used as such for distributed databases ala TiKV, for example), but it does not have SQL semantics on top of it, unlike Sqlite, which could prove useful.

In any case demonstrating we can quickly swap between store backends is benefitial so we are not stuck and coupled with one (and since right now we only need to maintain simple key-value semantics is rather easy to keep the backend implementation decoupled from the rest of the application, something we would like to continue in the future).

### PR DESCRIPTION
**Pull request by kakoc**
Closes #17  

Introduce rocksdb additionally to sqlite and make it default  

opened questions:
  - should we generalize a solution(create e.g. generic SqlDbError -> StorageDbError,  SQLiteContractHandler -> StorageContractHandler entities and have a specific rocksdb/sqlite "impls" for that? I played with a bit with such generelization and found too many generics there. I'm not sure that we need to do that(maintainability, extensebility, compile times, sqlite probably will be remove and rocksdb will be a single store)?

### CODE REVIEW

**Comment by kakoc** [comment]
Here some compile timings:

### without statically linked rocksdb; compiled with all features flag
Finished dev [unoptimized + debuginfo] target(s) in 11m 41s

### statically linked rocksdb; locutus compiled with default features only
Finished dev [unoptimized + debuginfo] target(s) in 5m 47s

### statically linked rocksdb; locutus compiled with all features
Finished dev [unoptimized + debuginfo] target(s) in 6m 47s

**Comment by iduartgomez** [comment]
> should we generalize a solution(create e.g. generic SqlDbError -> StorageDbError, SQLiteContractHandler -> StorageContractHandler entities and have a specific rocksdb/sqlite "impls" for that? I played with a bit with such generelization and found too many generics there. I'm not sure that we need to do that(maintainability, extensebility, compile times, sqlite probably will be remove and rocksdb will be a single store)?

I wanted to get rid of the generic error type and just use a boxed error instead in all the node where a generic was being used before, but haven't got to do it. Is annoying deal with it and totally not worth it, is pretty much a left over of an older version. If you want to tackle this in the PR, it will be welcomed, since it will likely simplify somethings a bunch. From memory but the error will have to be probably bounded (impl serialize, deserialize, send, sync etc.) but in practice this should not be a problem.

May do the same with other existing generics in the future, in general if we can avoid introducing more generics, we should avoid it for now until it proves worthfull. Boxing and dynamic dispatch in the context of the node should be ok in general performance wise, and if it helps with maintanibility we should go that route instead. 

I am not against using generics, but I need to revisit all this when we go back to modifying the node code to make the network version work and see how much worth it is to end up with generic soup which is annoying to maintain.

---

I will take a look into the PR later next week hopefully. Some open questions regarding building/linking, some of which we may be able to address now:
- Should we default to static linking the rocksdb deps? Imo, if possible yes. If it fails fall back to pulling anything from the network. We will need to review how is working re. sqlite and follow a similar strategy.
- For platforms where rocksdb may be problematic (if this is a real problem at all), we should fallback to using sqlite instead (sqlite platform support is excellent). We will have to make sure of this when we prepare release artifacts for the different platforms we want to support.
- At some point we probably want to look into some performance tests, but not necessary now.

All this will probably complicate the build process/compile config etc. unfortunately, but most likely necessary to do.

**Comment by kakoc** [comment]
I've played with linking of rocksdb a bit. I have several options to provide and I'm not sure which one we should pick up.  
So I suggest to introduce that in a separate PR if you wouldn't mind(so that it will be easier to test, revert, refer).

**Comment by iduartgomez** [comment]
Sure, no problem.

**Review by iduartgomez — APPROVED** [review]

**Comment by iduartgomez** [comment]
@kakoc apparently there are some conflicts, can you solve them and then we can merge the PR as it is.

Will will deal with the linking issues in an other PR/issue and simplifying the error generics.

**Comment by kakoc** [comment]
@iduartgomez, rebased

**Pull request merged**
