### PR TITLE
Command line ws API + typescript/js contract websocket API

### PR DESCRIPTION
**Pull request by sanity**

### CODE REVIEW

**Comment by sanity** [comment]
Just on directory structure, instead of `/contracts/freenet-microblogging` should it be `/apps/freenet-microblogging`?

**Comment by sanity** [comment]
Also, I'm not sure using the `model`/`view`/`web` terminology will be the easiest to understand, perhaps `freenet-microblogging` contains the typescript app, and then put the contract(s) in a `contracts` subfolder?

**Comment by iduartgomez** [comment]
> Also, I'm not sure using the `model`/`view`/`web` terminology will be the easiest to understand, perhaps `freenet-microblogging` contains the typescript app, and then put the contract(s) in a `contracts` subfolder?

but each of those folders must be packaged/compiled to be its own contract + state; isn't easier to bundle each contract together with it's "put" state?
so the "model" contract has its own contract code + initial state; the view contract has it's own state (which right now is just dummy, does nothing) and the web folder inside that is the state for the contract (in reality is the html files + the `bundle.js` file output by webpack)

p.s. still need to push changes where the packaging tool packages the state from a list of dirs/files in case that is confusing

**Comment by sanity** [comment]
> isn't easier to bundle each contract together with it's "put" state?

Hmm, not sure I'm following. Could you clarify what you mean by "put" state? Are you referring to the serialization format of the contract's state?

If it would be easier to discuss over video chat we could schedule one.

**Comment by iduartgomez** [comment]
Closes  #192

**Pull request merged**
